### ISSUE TITLE
Feature request: add expected overlap values to bar plots

### ISSUE THREAD

**Issue by capoony** [mw201608/SuperExactTest#2]
Dear Minghui,

It's me again. I wanted to kindly ask for a favour. Since I would like to visually present the expected vs. the observed overlap in the generic barplot output of SuperExactTest, I wanted to ask if there is an easy way to add this feature, e.g. by overlaying the observed value bars with semitransparent bars showing the expected overlap. I tried to do this myself but have difficulties to implement your nice feature to show the comparison by colored bullets underneath the bars.

Thanks a lot.

Best, Martin

**Comment by mw201608** [comment]
Hi Martin,

That is a very good suggestion. I will think about it and add this feature when I have a chance.

Regards,

Minghui

**Comment by mw201608** [comment]
Hi Martin,

Sorry for the late response but just had a chance to work on this request. There are now several new options (show.expected.overlap, expected.overlap.style, expected.overlap.lwd, color.expected.overlap and alpha.expected.overlap) which control whether and how to display expected overlap size. Please try update to v1.0.7 from github and let me know if there is any question.

Regards,

Minghui

**Comment by capoony** [comment]
Dear Minghui,

First of all, apologies for my delayed response! Unfortunately, I did not yet have time to test the update, but will do ASAP! This is awesome. Thanks a lot for implementing this feature, which will be really helpful.

Best, Martin

********************************************************
Martin Kapun, PhD

Senior Research Associate

Department of Evolutionary Biology and Environmental Studies
University of Zürich
34 (building)-J (floor)
Winterthurerstrasse 190
CH-8057 Zurich

Phone: +41 44 635 49 77 
https://www.researchgate.net/profile/Martin_Kapun

********************************************************
