### ISSUE TITLE
Save as PDF

### ISSUE THREAD

**Issue by ilibarra** [mw201608/SuperExactTest#3]
Dear mw201608,

Thank you for the development of this package.

I am intersecting multiple datasets and I would like to combine them using the UpSet visualization. For this I would like to save them as PDFs before editing. However, I get the following error when executing `plot.msets` on the `res` object instance:
```
            pdf(pdf_path, width=w, height=h)
            plot.msets(res)
            dev.off()
```
```
Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  :
  Viewport has zero dimension(s)
```

Is there an example for saving PDFs? So far I just see an example for PNGs.

Thank you,
Ignacio

**Comment by ilibarra** [comment]
Solved. It was about giving higher values for width and height (>= 10 for big intersection queries). Thanks!

**Comment by mw201608** [comment]
Great you solved the problem!
