### ISSUE TITLE
Memory exception in specific cases [attached]

### ISSUE THREAD

**Issue by ilibarra** [mw201608/SuperExactTest#4]
Hi,

In the following attached example I get a memory error. Is there any obvious reason for this? I have observed this ~3-4 times in 20 cases that I have run in bulk.
https://www.dropbox.com/s/cw534rczhwy34pe/debugCaseSuperExactTest.rds?dl=0
```
events <- readRDS('debugCaseSuperExactTest.rds') # total = 1010
total <- 1010 # this is the number of rows in the original dataframe
res=supertest(events, n=total)
*** Error in `/g/scb/zaugg/rio/miniconda2/lib/R/bin/exec/R': double free or corruption (!prev): 0x0000000002598720 ***
======= Backtrace: =========
```

Thanks!
Ignacio

**Comment by mw201608** [comment]
Ignacio,

Thanks for reporting the memory issue. I have fixed the bug. Can you please update the package to the latest version from github and test again. Let me know if there is any question.

Regards,

Minghui
