### ISSUE TITLE
show expected values in logscale when log.scale=T

### ISSUE THREAD

**Issue by ilibarra** [mw201608/SuperExactTest#5]
Dear mw201608,

Thank you for the development and active maintaining of SuperExactTest

Under this combination of values, log.scale is not applied to the show.expected.overlap white bars. They end up rescaling outside of the ylim shown upon applying log.scale.

Is this something that can be tested/confirmed? Maybe I am not having something alright. Happy to send input files in any case.
```
plot(res, Layout="landscape", sort.by='p-value', log.scale=T, show.expected.overlap=T,
    elements.list=t1, elements.rot=0, show.elements=T, color.on='black', color.off='white',
     legend.text.cex=2.0, ylim = c(0, 2000),
    show.expected.overlap=TRUE, expected.overlap.style="box", expected.overlap.lwd=0.4,
    overlap.size.cex=1.0, intersection.size.rotate=T,  flip.vertical=F)
```

Best regards,

**Comment by mw201608** [comment]
Hi ilibarra,

Thanks for reporting this bug. Sorry for the delayed response as I just found this issue. Please install the latest the version from Github to fix the bug. Let me know if there is any question.

Regards,

Minghui
