### ISSUE TITLE
Save the plot as pdf and multiple same plots were generated

### ISSUE THREAD

**Issue by Guan06** [mw201608/SuperExactTest#6]
Hi,

thanks for developing this nice tool!

I ran into a problem when I was trying to export the plot into pdf. A multi-pages plots were generated with same figure. I think this is only the case for the landscape layout.

Could you please take a look into the issue?

Many thanks!
Rui

**Comment by mw201608** [comment]
Hi Rui,

Thanks for reporting the bug. It appears the issue happens when argument "bar.split" is used. Let me know if this is not the case in your situation. I have fixed this bug in the new v1.1.1. Please update the package from GitHub and let me know if problem resolves.

Thanks,

Minghui

**Comment by Guan06** [comment]
> Hi Rui,
> 
> Thanks for reporting the bug. It appears the issue happens when argument "bar.split" is used. Let me know if this is not the case in your situation. I have fixed this bug in the new v1.1.1. Please update the package from GitHub and let me know if problem resolves.
> 
> Thanks,
> 
> Minghui

Hi Minghui,

many thanks for your prompt reply.

Yes you are correct, the problem was due to "bar.split" and with the new version it is fixed.

Thanks again and best regards,
Rui
