### ISSUE TITLE
Plotting Pvalue Adjustment

### ISSUE THREAD

**Issue by ivingan01** [mw201608/SuperExactTest#7]
I'm a bit of a novice coder, so this is an overlap of a general "how to" question, and a question specific for this package.

I intend to use this software to look for the overlap between 6 different lists. I am grateful for how simple and approachable this was. However, 6 lists lends itself to 57 (63-6) hypotheses tested on over laps. 

Very simply, I would like to run multiple hypothesis test correction on the results of the analysis AND plot these results using the plot functions outlined in the vignettes. 

The closest I have been able to get is saving the summary table as its own variable and then adding a new column with the adjusted p values. 

`res_table <- summary(res)$Table
res_table$padj <- stats::p.adjust(res_table %>% pull(., P.value), method = "BH", n = length(res_table %>% pull(., P.value)))
`

But now that this is a separate table and not the S3 class object, it is incompatible with plot function. How do i add these adjusted p values to the S3 class object and then select to plot those instead of the P.value column?

Thank you for the help!

**Comment by mw201608** [comment]
Hi,

This is a very good question. The supertest function outputs a "msets" class object (basically a list), with one entry named "P.value" containing the P values. You can check ?msets for explanation. A simple trick for your purpose is to manually replace the res$P.value with the corrected P values.

Minghui

**Comment by ivingan01** [comment]
Quick and simple solution. That worked without a hitch. Thank you! Now I'm off to learn more about the R::plot() function to beautify the plot.
