### ISSUE TITLE
Plotting a defined number of bars

### ISSUE THREAD

**Issue by lucasrocmoreira** [mw201608/SuperExactTest#8]
Hi,

Thanks for the package. It is very useful, flexible, and well-documented.

I am currently comparing 9 sets which results in 511 combinations of intersection. I want to select specific intersections to plot (which can be achieved by sorting the data in a pre-defined order), but I cannot figure out how to select the number of bars to show. Say, I'm interested in plotting only the first 10 bars. How would I do that? I would appreciate any suggestions.

Best,
Lucas

**Comment by mw201608** [comment]
Lucas,

You can manipulate the supertest result object to achieve what you want. Check the example below for plotting overlaps larger than a threshold.

```
library(SuperExactTest)
#create some random sets
set.seed(1234)
n <- 400
r_strings <- do.call(paste0, replicate(5, sample(LETTERS, n, TRUE), FALSE))
input <- lapply(c(40, 60, 80, 200), function(x,s) sample(s,x), s=r_strings)
#do SuperExactTest
Result <- supertest(input, n=n)
#Subset the overlaps with size >= 5
Result2 <- Result
Result2$overlap.sizes <- Result2$overlap.sizes[Result2$overlap.sizes >= 5]
Result2$overlap.expected <- Result2$overlap.expected[names(Result2$overlap.sizes)]
Result2$P.value <- Result2$P.value[names(Result2$overlap.sizes)]
#PLot both the full result and the selected overlaps
grid.newpage()
vp0 <- viewport(layout = grid.layout(1, 2))
vp1 <- viewport(layout.pos.col = 1, layout.pos.row = 1, name = "plot_left")
vp2 <- viewport(layout.pos.col = 2, layout.pos.row = 1, name = "plot_right")
vps <- vpTree(vp0, vpList(vp1, vp2))
pushViewport(vps)
seekViewport("plot_left")
plot(Result, Layout = 'landscape', degree = 2:length(input), sort.by = 'size', new.gridPage = FALSE)
seekViewport("plot_right")
plot(Result2, Layout = 'landscape', degree = 2:length(input), sort.by = 'size', new.gridPage = FALSE)
```

**Comment by mw201608** [comment]
You can may also follow the new example in the [README "2 Sort and/or subset intersection bars for plotting".](https://github.com/mw201608/SuperExactTest/blob/master/README.md#2-sort-andor-subset-intersection-bars-for-plotting).

**Comment by lucasrocmoreira** [comment]
Thanks, that helps.
